name: "Terraform Formatting Check"
on: [push]
jobs:
  terraform:
    name: "Terraform Formatting Check"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Terraform Formating Check
        run: | 
          terraform fmt -recursive -check -diff
